### ISSUE TITLE
change-year

### ISSUE THREAD

**Issue by haager-ca** [multimediaAG/Adventskalender#72]

**Comment by Saturn56** [comment]
ist schon mit Variablen automatisch gemacht

**Comment by hrueger** [comment]
Hi,
in der Backend-Logik war das Jahr hardcoded (ich weiß grad nicht, ob das immer noch so ist). Das Problem ist sonst, dass am 01.01.23 die Ergebnisse nicht mehr angezeigt werden, weil er meint, wir hätten ja noch nicht Dezember.
Das könnte man bestimmt mit etwas komplexerer Logik lösen, die beispielsweise das aktuelle Jahr um 1 reduziert, wenn wir noch nicht Juni haben, aber dazu hatte ich letztes Jahr keine Lust ;-)

**Comment by haager-ca** [comment]
das Issue muss noch warten, bis das Backend wieder läuft

**Comment by haager-ca** [comment]
Und dann muss noch ein Commit durchgeführt werden. Erklär ich später nochmal
